// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpeninHidemaruEditor
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCommand1PackageString = "24134a27-a710-4c73-8544-88cdc6fb9056";
        public static Guid guidCommand1Package = new Guid(guidCommand1PackageString);

        public const string guidCommand1PackageCmdSetString = "610d7b6f-5697-40cd-b3c4-a1dca9011d91";
        public static Guid guidCommand1PackageCmdSet = new Guid(guidCommand1PackageCmdSetString);

        public const string guidIconsString = "599355fd-49d0-4ca5-81cd-c5361f56d54f";
        public static Guid guidIcons = new Guid(guidIconsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int Command1Id = 0x0100;
        public const int MyMenuGroup = 0x1020;
        public const int HidemaruEditor = 0x0001;
    }
}